name: Build documentation
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  build-docs:
    runs-on: ubuntu
    steps:
      - uses: opentelekomcloud-infra/github-actions/.github/actions/tox-run-env@v1
        with:
          tox-env: docs
